CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    billing_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    transactions_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    inventory_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    analytics_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ai_assistant_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    default_pharmacy_id BIGINT,
    logo_file_name VARCHAR(255),
    logo_content_type VARCHAR(120),
    logo_data BYTEA,
    CONSTRAINT uk_tenants_code UNIQUE (code)
);
CREATE TABLE IF NOT EXISTS pharmacies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    logo_file_name VARCHAR(255),
    logo_content_type VARCHAR(120),
    logo_data BYTEA,
    CONSTRAINT uk_pharmacy_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT fk_pharmacies_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    tenant_id BIGINT,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    default_pharmacy_id BIGINT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    phone_number VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255),
    birthdate VARCHAR(255),
    gender VARCHAR(255),
    CONSTRAINT uk_users_tenant_username UNIQUE (tenant_id, username),
    CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_users_default_pharmacy FOREIGN KEY (default_pharmacy_id) REFERENCES pharmacies(id)
);
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS user_pharmacies (
    user_id BIGINT NOT NULL,
    pharmacy_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, pharmacy_id),
    CONSTRAINT fk_user_pharmacies_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_pharmacies_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES pharmacies(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    batch_number VARCHAR(255) NOT NULL,
    tenant_id BIGINT NOT NULL,
    pharmacy_id BIGINT NOT NULL,
    expiry_date DATE NOT NULL,
    supplier VARCHAR(255) NOT NULL,
    unit_type VARCHAR(50) NOT NULL,
    purchase_price DECIMAL(12, 2) NOT NULL,
    selling_price DECIMAL(12, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT uk_medicine_tenant_pharmacy_batch UNIQUE (tenant_id, pharmacy_id, batch_number),
    CONSTRAINT fk_medicines_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_medicines_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES pharmacies(id)
);
CREATE TABLE IF NOT EXISTS medicine_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id BIGINT NOT NULL,
    modification_reason VARCHAR(1000) NOT NULL,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_medicine_audit_logs_medicine FOREIGN KEY (medicine_id) REFERENCES medicines(id)
);
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(255) NOT NULL,
    tenant_id BIGINT NOT NULL,
    pharmacy_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_before_discount DECIMAL(12, 2) NOT NULL,
    discount_amount DECIMAL(12, 2) NOT NULL,
    total_after_discount DECIMAL(12, 2) NOT NULL,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(255),
    created_by_id BIGINT NOT NULL,
    CONSTRAINT uk_sales_transaction_id UNIQUE (transaction_id),
    CONSTRAINT fk_sales_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sales_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES pharmacies(id),
    CONSTRAINT fk_sales_created_by FOREIGN KEY (created_by_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    medicine_name_snapshot VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_type VARCHAR(255) NOT NULL,
    dosage_instruction VARCHAR(255),
    custom_dosage_instruction VARCHAR(255),
    remark VARCHAR(255),
    unit_price DECIMAL(12, 2) NOT NULL,
    unit_cost DECIMAL(12, 2) NOT NULL,
    line_total DECIMAL(12, 2) NOT NULL,
    line_cost DECIMAL(12, 2) NOT NULL,
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id),
    CONSTRAINT fk_sale_items_medicine FOREIGN KEY (medicine_id) REFERENCES medicines(id)
);
CREATE TABLE IF NOT EXISTS tenant_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    action VARCHAR(80) NOT NULL,
    performed_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tenant_audit_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);
CREATE TABLE IF NOT EXISTS stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    data BYTEA NOT NULL,
    size BIGINT NOT NULL,
    sale_id BIGINT NOT NULL,
    uploaded_by_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stored_files_sale FOREIGN KEY (sale_id) REFERENCES sales(id),
    CONSTRAINT fk_stored_files_uploaded_by FOREIGN KEY (uploaded_by_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_users_tenant ON users (tenant_id);
CREATE INDEX IF NOT EXISTS idx_pharmacies_tenant ON pharmacies (tenant_id);
CREATE INDEX IF NOT EXISTS idx_medicines_tenant_pharmacy ON medicines (tenant_id, pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_sales_tenant_pharmacy_created_at ON sales (tenant_id, pharmacy_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_stored_files_sale ON stored_files (sale_id);
CREATE INDEX IF NOT EXISTS idx_tenant_audit_logs_tenant_created_at ON tenant_audit_logs (tenant_id, created_at);

